language: minimal

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

os: linux

services:
  - docker

env:
  - HAZELCAST_IMAGE=hazelcast-oss

install:
  - docker build -t $HAZELCAST_IMAGE $HAZELCAST_IMAGE

script:
  - docker images
  - |
    PROMETHEUS_PORT=8080
    if [ "$HAZELCAST_IMAGE" = "hazelcast-oss" ]; then
      docker run -it --name ${HAZELCAST_IMAGE}-container --rm $HAZELCAST_IMAGE
      # sleep 10
      # HZ_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${HAZELCAST_IMAGE}-container)
      # nc -z $HZ_IP 5701
    fi

notifications:
  email:
    recipients:
      - muhammet.yazici@hazelcast.com
    on_success: never
    on_failure: always
