name: Build EE snapshot image

on:
  workflow_dispatch:
    inputs:
      HZ_VERSION:
        description: 'Version of Hazelcast to build the image for'
        required: true
      HZ_EE_REVISION:
        description: 'Commit id of Hazelcast Enterprise snapshot jar'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build EE image
        run: |
          docker build \
            --build-arg HZ_VERSION=${{ github.event.inputs.HZ_VERSION }} \
            --label hazelcast.ee.revision=${{ github.event.inputs.HZ_EE_REVISION }} \
            --tag mtypey/hazelcast-enterprise:${{ github.event.inputs.HZ_VERSION }} hazelcast-enterprise

      - name: Push EE image
        run: |
          docker push mtypey/hazelcast-enterprise:${{ github.event.inputs.HZ_VERSION }}

