name: Build OSS snapshot image

on:
  workflow_dispatch:
    inputs:
      HZ_VERSION:
        description: 'Version of Hazelcast to build the image for'
        required: true
      HZ_REVISION:
        description: 'Commit id of Hazelcast snapshot jar'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build OSS image
        run: |
          docker build \
            --build-arg HZ_VERSION=${{ github.event.inputs.HZ_VERSION }} \
            --label hazelcast.revision=${{ github.event.inputs.HZ_REVISION }} \
            --tag mtypey/hazelcast:${{ github.event.inputs.HZ_VERSION }} hazelcast-oss

      - name: Push OSS image
        run: |
          docker push mtypey/hazelcast:${{ github.event.inputs.HZ_VERSION }}
